const express=require('express')

// const  {allProducts,deleteUsers} = require('../controllers/products-controller')
// const  {allUsers,postUsers,updateUsers} = require('../controllers/login-controllers')
const {allCartProducts,deleteCartProducts,updateCartProducts,postCartProducts} = require('../controllers/cart-controller')
const allHistory = require('../controllers/order-controller')
const ProductController = require('../controllers-1/product-controller')
const users = require('../controllers-1/login-controller')
const CartController = require('../controllers-1/cart-controller')
const route=express.Router()
const products=new ProductController()
const cart=new CartController()
 route.get('/users/:id?',products.getAllProducts)
//  route.get('/login/:id?',allUsers)
route.get('/login/:id?',users.getAllUsers)
// route.post("/login",postUsers)
route.post("/login",users.postUsers);
route.put('/login/:id',users.updateUser)
route.get('/cart',cart.allCartProducts)
route.post('/cart',cart.createCartProducts)
route.delete('/cart/:id',deleteCartProducts)
route.put('/cart/:id',updateCartProducts)
route.get('/history',allHistory)
module.exports=route

