const express=require('express')
const ProductController = require('../controllers-1/product-controller')
const users = require('../controllers-1/login-controller')
const CartController = require('../controllers-1/cart-controller')
const HistoryController = require('../controllers-1/history-controller')
const route=express.Router()
const products=new ProductController()
const cart=new CartController()
const history=new HistoryController()
 route.get('/users/:id?',products.getAllProducts)
route.get('/login/:id?',users.getAllUsers)
route.post("/login",users.postUsers);
route.put('/login/:id',users.updateUser)
route.get('/cart',cart.allCartProducts)
route.post('/cart',cart.createCartProducts)
route.delete('/cart/:id',cart.deleteCartProducts)
route.put('/cart/:id',cart.updateCartProducts)
route.get('/history',history.allHistories)
route.post('/history',history.postHistories)
module.exports=route

